# Site settings
title: jekyll-test 
email: hdfelix@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  For now this site is just to get familiar wtih jekyll
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: hafelix 
github_username: hdfelix 

# Build settings
markdown: kramdown
highlighter: rouge
