# Site settings
title: jekyll-test 
email: hdfelix@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  For now this site is just to get familiar wtih jekyll
baseurl: "/jekyll-test" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: hafelix 
#github_username: hdfelix 

# analytics:
#   google:
#     id: UA-1721142-2
#     domain:
exclude: 
  - vendor
  - README.md
  - GEMFILE
  - GEMFILE.lock

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

# Site defaults
# defaults:
